### ISSUE TITLE
Image turning black on paint.c

### ISSUE THREAD

**Issue by gu-ma** [yui0/catseye#1]
Hi,

Thanks for sharing the library, it's working pretty well :) I just have an issue with "paint.c" I've been trying it on different images and on the output video, after 2 or 3 seconds the image is turning black, couldn't figure out why... 

[paint.mp4.zip](https://github.com/yui0/catseye/files/573543/paint.mp4.zip)

Thanks,

Guillaume

**Comment by yui0** [comment]
Hello,

Thank you for using catseye. I checked your information about paint.c and I found a bug that CatsEye_act_tanh function is broken. So please use the new version.

Regards,
Yuichiro Nakada
